.\" This file is distributed under the same license as the ibus
.\" package.
.\" Copyright (C) LI Daobing <lidaobing@gmail.com>, 2008.
.\"
.TH "IBUS" 1 "2008-11-08" "" ""
.SH NAME
ibus \- Intelligent Input Bus for Linux / Unix OS

.SH "DESCRIPTION"

.PP
IBus is an Intelligent Input Bus. It is a new input framework for Linux
OS. It provides full featured and user friendly input method user
interface.  It also may help developers to develop input method easily.  

.PP
Homepage: http://code.google.com/p/ibus/

.SH "NOTES"

.PP
if you are using gdm or kdm, run the following command, then restart your gdm or kdm.
.TP
$ im-switch -s ibus

.PP
if you are using startx, add the following command to $HOME/.xinitrc

.PP
ibus-daemon -xd

.PP
if you want to debug ibus, run the following command

.PP
$ ibus-daemon -xvr


.SH "SEE ALSO"
.BR ibus-daemon (1),
.BR ibus-setup (1),
.BR scim (1),
.BR fcitx (1)
